[mmn]
  api-key = "u2PJZzlogtwIdXUB9v7ZzTAqwT9wwkAFgSQJajF5"

[openvpn]
  price-gb = 0.2
  price-minute = 0.00005

[payment]
  price-gb = 0.2
  price-minute = 0.0001

[shaper]
  enabled = false

[terms]
  consumer-agreed = true
  provider-agreed = true
  version = "0.0.27"

[wireguard]
  price-gb = 1.99
  price-minute = 0.00005
